[versions]
kotlin = "1.9.23"
composeMultiplatform = "1.6.10"
junit = "4.13.2"
kotlinx-coroutines = "1.8.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

# Las dependencias de lifecycle son válidas para Compose 1.6.10
compose-lifecycle-runtime-compose = { module = "org.jetbrains.compose.lifecycle:lifecycle-runtime-compose", version.ref = "composeMultiplatform" }
compose-lifecycle-viewmodel-compose = { module = "org.jetbrains.compose.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeMultiplatform" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
